<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT0bmbzv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT0bmbzv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT0bmbzv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT0bmbzv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT0bmbzv\appProdProjectContainer([
    'container.build_hash' => 'T0bmbzv',
    'container.build_id' => '5bb41c47',
    'container.build_time' => 1733069332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT0bmbzv');
