<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhwtyvy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhwtyvy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFhwtyvy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFhwtyvy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFhwtyvy\appProdProjectContainer([
    'container.build_hash' => 'Fhwtyvy',
    'container.build_id' => '225ab146',
    'container.build_time' => 1729113563,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhwtyvy');
