<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsfdkqo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsfdkqo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOsfdkqo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOsfdkqo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOsfdkqo\appDevDebugProjectContainer([
    'container.build_hash' => 'Osfdkqo',
    'container.build_id' => '2c523f7a',
    'container.build_time' => 1733860867,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsfdkqo');
